### ISSUE TITLE
设计模式和重构

### ISSUE THREAD

**Issue by CwjXFH** [liqingwen2015/designPatterns#1]
推荐个网站：[Refactoring and Design Patterns](https://refactoring.guru/)

**Comment by liqingwen2015** [comment]
好的

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: WenJun ***@***.***>
发送时间: 2021年6月7日 9:41
收件人: ***@***.***>
抄送: ***@***.***>
主题: [liqingwen2015/designPatterns] 设计模式和重构 (#1)


推荐个网站：Refactoring and Design Patterns<https://refactoring.guru/>

―

**Comment by liqingwen2015** [comment]
谢谢
